---
domain: jepolitsch.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://jepolitsch.github.io  # the base hostname and protocol for your site, e.g. http://example.com
title: Julian Politsch
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Personal Site
theme: jekyll-theme-midnight
show_downloads: false
